#!/usr/bin/env bash

cd ../..
# the archive goes out as the version that CMakeLists.txt downloads, which
# new data have to raise first [see DATA_VERSION there]
bash upload-to-package-registry SVMBlock/data/libsvm.tgz \
     "$(sed -n 's/^set(DATA_VERSION \(.*\))$/\1/p' SVMBlock/CMakeLists.txt)"
